# Generated by Django 3.2.9 on 2021-11-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='lastReviewed',
            new_name='last_reviewed_date',
        ),
    ]
