# Generated by Django 3.2.9 on 2021-11-15 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_deck_last_reviewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
