# Generated by Django 3.2.9 on 2021-11-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=128)),
                ('answer', models.TextField(max_length=1000)),
                ('nextReviewDate', models.DateTimeField()),
                ('lastReviewedDate', models.DateTimeField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.buckets')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
        ),
    ]
