# Generated by Django 3.2.9 on 2021-11-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='lastReviewedDate',
            new_name='last_reviewed_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='nextReviewDate',
            new_name='next_review_date',
        ),
    ]
