# Generated by Django 3.2.9 on 2021-11-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20211115_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '3 Day'), (3, '7 Day'), (4, '15 Day'), (5, '30 Day')]),
        ),
    ]
