# Generated by Django 3.2.9 on 2021-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
