# Generated by Django 3.2.9 on 2021-11-15 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20211115_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
