# Generated by Django 3.2.9 on 2021-11-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_next_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '3 Day'), (3, '7 Day'), (4, '15 Day'), (5, '30 Day')], default=1),
        ),
    ]
